### ISSUE TITLE
POLARIS-HTML-BLOG

### ISSUE THREAD

**Issue by debasiskar-devel-007** [debasiskar-devel-007/polaris-next#4]
https://drive.google.com/drive/u/0/folders/1agKLR-w-4axSbaJcYLR9H3upkqqlOqjh

**Comment by Biswarup2000** [comment]
"POLARIS - HTML - BLOG Blog page full image HTML CSS update done[[bill-01:00-4-02192024]]"

**Comment by Biswarup2000** [comment]
"POLARIS - HTML - BLOG Blog page full image header navbar and footer update[[bill-01:00-4-02192024]]"
